import React, { useEffect, useState } from 'react';
import { Activity, AlertTriangle, Bot, ClipboardCheck, Download, Flame, Gauge, LoaderCircle, MapPin, Pause, Play, Save, Send, ShieldCheck, SlidersHorizontal, Thermometer, Waves, X } from 'lucide-react';
import './console.css';
import { applyOptimization, connectWellWebSocket, fetchFieldSummary, fetchWellActions, fetchWellTelemetry, sendChatMessage, updateWellControls } from './services/api';

const n = (v, d = 0) => v == null ? '—' : Number(v).toLocaleString('en-IN', { maximumFractionDigits: d });
const phases = { INJECTION: 'Steam injection', SOAKING: 'Heat soak', PRODUCTION: 'Production' };

export default function App() {
  const [field, setField] = useState(null), [wellId, setWellId] = useState('BGW-01'), [t, setT] = useState(null), [actions, setActions] = useState([]);
  const [connected, setConnected] = useState(false), [busy, setBusy] = useState(false), [notice, setNotice] = useState(null), [reply, setReply] = useState(''), [question, setQuestion] = useState('');
  const [draft, setDraft] = useState({ spm: 0, choke_pct: 70 }), [market, setMarket] = useState({ crude_price_usd_bbl: 75, steam_cost_usd_ton: 18, electricity_cost_usd_kwh: .12 });
  const [paused, setPaused] = useState(false);
  const goTo = id => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' });
  const getActions = async id => { const r = await fetchWellActions(id || wellId); if (r) setActions(r.actions || []); };
  useEffect(() => { const load = async () => setField(await fetchFieldSummary()); load(); const timer = setInterval(load, 8000); return () => clearInterval(timer); }, []);
  useEffect(() => {
    let ws;
    const poll = async () => {
      if (paused) return;
      const r = await fetchWellTelemetry(wellId);
      if (r) { setT(r); setConnected(true); }
    };
    (async () => {
      const r = await fetchWellTelemetry(wellId);
      if (r) { setT(r); setConnected(true); setDraft({ spm:r.spm, choke_pct:r.choke_pct }); }
      getActions(wellId);
      ws = connectWellWebSocket(wellId, x => { if (!paused) { setT(x); setConnected(true); } }, () => setConnected(false));
    })();
    const timer = setInterval(poll, 6000);
    return () => { ws?.close(); clearInterval(timer); };
  }, [wellId, paused]);
  const save = async updates => { setBusy(true); const r = await updateWellControls(wellId, updates); setBusy(false); if (r) { setT(r); setDraft({ spm:r.spm, choke_pct:r.choke_pct }); getActions(); setNotice(['success','Setpoint saved to the simulated twin.']); } else setNotice(['error','Could not save. Check the FastAPI service.']); };
  const evaluate = async () => { setBusy(true); const r = await applyOptimization(wellId, market); setBusy(false); if (r) { setT(r); getActions(); setNotice(['info','Scenario evaluated. Review its risk flag before accepting.']); } else setNotice(['error','Scenario evaluation failed. Check the FastAPI service.']); };
  const ask = async preset => { const q = preset || question; if (!q) return; setBusy(true); setQuestion(''); const r = await sendChatMessage(wellId, q); setBusy(false); setReply(r?.response || 'Assistant unavailable.'); };
  const exportData = () => { const url = URL.createObjectURL(new Blob([JSON.stringify({ exported_at:new Date().toISOString(), source:'SIMULATED_DEMO', telemetry:t, actions }, null, 2)],{type:'application/json'})); const a=document.createElement('a'); a.href=url;a.download=`${wellId}-twin-snapshot.json`;a.click();URL.revokeObjectURL(url); };
  const css=t?.css_physics, srp=t?.srp_physics, hyd=t?.hydraulics, opt=t?.optimization, fault=srp?.anomaly_detected && !['NORMAL','INJECTION_STANDBY'].includes(srp.anomaly_detected);
  return <main className="ops-shell"><aside className="ops-sidebar"><div className="brand"><div className="brand-mark"><Waves size={19}/></div><div><b>OILFIELD</b><span>OPERATIONS TWIN</span></div></div><div className="site-label"><MapPin size={14}/><span>Baghewala · Rajasthan</span></div><nav><button className="active" onClick={()=>goTo('operations')}><Activity size={17}/>Operations desk</button><button onClick={()=>goTo('css-cycle')}><Flame size={17}/>CSS cycle plan</button><button onClick={()=>goTo('artificial-lift')}><Gauge size={17}/>Artificial lift</button><button onClick={()=>goTo('decision-log')}><ClipboardCheck size={17}/>Decision log</button></nav><div className="side-foot"><span className="eyebrow">Data environment</span><strong><i className={`status-dot ${connected?'online':''}`}/> SIMULATED TWIN</strong><p>Hackathon demonstration only. Field deployment needs historian integration and operator approval.</p></div></aside>
  <section className="ops-content"><header className="topbar"><div><span className="eyebrow">Well-to-surface decision support</span><h1>Baghewala operations desk</h1><p>CSS thermal recovery and SRP lift performance in one operating view.</p></div><div className="top-actions"><button className="button secondary" onClick={()=>setPaused(!paused)}>{paused?<Play size={15}/>:<Pause size={15}/>}{paused?'Resume feed':'Pause feed'}</button><span className={`connection ${connected && !paused?'live':''}`}><i className="status-dot"/>{paused?'Stream paused':connected?'Live simulated feed':'Connecting'}</span><button className="button secondary" onClick={exportData}><Download size={15}/>Export snapshot</button></div></header>
  {notice&&<div className={`notice ${notice[0]}`}><span>{notice[1]}</span><button onClick={()=>setNotice(null)}><X size={15}/></button></div>}
  <section className="well-strip"><div className="well-strip-head"><div><span className="eyebrow">Field inventory</span><strong>{field?`${field.active_wells_count} modelled wells`:'Loading inventory'}</strong></div><span>OIL reference: Jodhpur Sandstone, ~1,150 m</span></div><div className="well-tabs">{(field?.wells||[]).map(w=><button key={w.well_id} onClick={()=>setWellId(w.well_id)} className={w.well_id===wellId?'selected':''}><i className={`well-icon ${w.anomaly!=='NORMAL'&&w.anomaly!=='INJECTION_STANDBY'?'warning':''}`}>{w.anomaly!=='NORMAL'&&w.anomaly!=='INJECTION_STANDBY'?<AlertTriangle size={14}/>:<Activity size={14}/>}</i><span><b>{w.well_id}</b><small>{phases[w.phase]||w.phase}</small></span><em>{w.phase==='PRODUCTION'?`${n(w.oil_rate_bopd,1)} BOPD`:'CSS active'}</em></button>)}</div></section>
  <section className="hero-grid"><article className="well-card"><div className="card-header"><div><span className="eyebrow">Selected asset</span><h2>{t?.well_name||wellId}</h2></div><span className={`pill ${fault?'danger':'good'}`}>{fault?srp.anomaly_detected.replace('_',' '):t?'OPERATING NORMALLY':'LOADING'}</span></div><div className="metric-row"><Metric label="Oil rate" value={`${n(t?.oil_rate_bopd,1)} BOPD`} icon={<Activity/>}/><Metric label="Pump speed" value={`${n(t?.spm,1)} SPM`} icon={<Gauge/>}/><Metric label="Pump fillage" value={`${n(srp?.pump_fillage_pct)}%`} icon={<Waves/>}/><Metric label="Reservoir temp." value={`${n(css?.reservoir_temp_c)} °C`} icon={<Thermometer/>}/></div><div className="well-path"><Point label="Reservoir" value={`${n(hyd?.reservoir_pressure_bar,1)} bar`}/><Point label="Pump intake" value={`${n(hyd?.pump_intake_pressure_bar,1)} bar`}/><Point label="Wellhead" value={`${n(hyd?.wellhead_pressure_bar,1)} bar`}/><Point label="Separator" value={`${n(hyd?.separator_pressure_bar,1)} bar`}/></div></article><article className="shift-card"><span className="eyebrow">Shift decision</span><h2>{fault?'Protect the rod pump before increasing drawdown.':'Maintain surveillance; test the economic operating window.'}</h2><p>{actions[0]?.detail||'No operator actions recorded for this well.'}</p><div className="shift-footer"><ShieldCheck size={17}/><span>Human approval remains in the control path</span></div></article></section>
  <section className="dashboard-grid"><article className="panel css-panel"><Title icon={<Flame/>} title="CSS cycle control" detail={t?`Day ${t.days_in_phase} · ${phases[t.phase]}`:'Loading'}/><div className="phase-track">{Object.entries(phases).map(([key,label],i)=><button key={key} className={t?.phase===key?'current':''} onClick={()=>save({phase:key})}><span>{i+1}</span><b>{label}</b><small>{key==='INJECTION'?'Steam / pump off':key==='SOAKING'?'Heat diffusion':'Lift enabled'}</small></button>)}</div><div className="thermal-grid"><Item label="Thermal radius" value={`${n(css?.heated_radius_m,1)} m`} sub="Modelled heated zone"/><Item label="Oil viscosity" value={`${n(css?.oil_viscosity_cp)} cP`} sub="At modelled temperature"/><Item label="Cumulative SOR" value={`${n(css?.csor,2)} bbl/bbl`} sub="Steam / produced oil"/></div><div className="model-note"><ShieldCheck size={15}/><span>Phase transitions apply safe simulated controls; they are not automatic field instructions.</span></div></article>
  <article className="panel lift-panel"><Title icon={<SlidersHorizontal/>} title="SRP operating envelope" detail={srp?.anomaly_detected?.replace('_',' ')||'Loading'}/><Range label="Polished-rod speed" value={draft.spm} unit="SPM" min="0" max="10" step=".1" disabled={t?.phase!=='PRODUCTION'} onChange={v=>setDraft(d=>({...d,spm:v}))}/><Range label="Choke opening" value={draft.choke_pct} unit="%" min="20" max="100" onChange={v=>setDraft(d=>({...d,choke_pct:v}))}/><div className="lift-metrics"><Item label="Peak rod load" value={`${n(srp?.peak_load_lb)} lbf`}/><Item label="Torque" value={`${n(srp?.peak_torque_k_in_lb,1)} k-in·lbf`}/><Item label="Power" value={`${n(srp?.power_kw,1)} kW`}/></div><button className="button dark full" disabled={busy||t?.phase!=='PRODUCTION'} onClick={()=>save(draft)}><Save size={15}/>Save operating setpoint</button></article>
  <article className="panel optimizer-panel"><Title icon={<Gauge/>} title="Constrained scenario optimizer" detail="Physics-informed search · 121 candidates"/><p className="panel-copy">Evaluate a bounded SPM/choke window with your market inputs. It flags equipment risk; it does not auto-control the well.</p><div className="economics"><EconomicInput label="Crude / bbl" value={market.crude_price_usd_bbl} step="1" onChange={v=>setMarket(s=>({...s,crude_price_usd_bbl:v}))}/><EconomicInput label="Steam / tonne" value={market.steam_cost_usd_ton} step="1" onChange={v=>setMarket(s=>({...s,steam_cost_usd_ton:v}))}/><EconomicInput label="Power / kWh" value={market.electricity_cost_usd_kwh} step=".01" onChange={v=>setMarket(s=>({...s,electricity_cost_usd_kwh:v}))}/></div><button className="button primary full" disabled={busy||!t} onClick={evaluate}>{busy?<LoaderCircle className="spin" size={16}/>:<Play size={16}/>}Evaluate scenario</button>{opt&&<div className="recommendation"><span className="eyebrow">Recommended reviewed target</span><strong>{n(opt.target_spm,1)} SPM <i/> {n(opt.target_choke_pct)}% choke</strong><p>{opt.recommendations?.[0]}</p><em className={`risk ${opt.selected_scenario?.risk_flag==='NORMAL'?'normal':''}`}>{opt.selected_scenario?.risk_flag?.replace('_',' ')}</em><div className="money"><span>Estimated margin change</span><b>{opt.potential_gain_usd_day>=0?'+':''}${n(opt.potential_gain_usd_day)}/day</b></div><button className="button approve" disabled={busy||opt.decision_status!=='REVIEW_REQUIRED'} onClick={()=>save({spm:opt.target_spm,choke_pct:opt.target_choke_pct,steam_rate_tpd:opt.target_steam_tpd})}><ClipboardCheck size={15}/>Accept after review</button></div>}</article>
  <article className="panel assistant-panel"><Title icon={<Bot/>} title="Operations assistant" detail="Current twin context"/><p className="panel-copy">Domain guidance grounded in the simulated well snapshot, not an unverified LLM claim.</p><div className="assistant-prompts"><button onClick={()=>ask('Diagnose the current rod-pump condition and explain the safe next check.')}>Diagnose lift condition <Send size={13}/></button><button onClick={()=>ask('What CSS phase gate should the operator review for this well?')}>Review CSS phase gate <Send size={13}/></button></div>{reply&&<div className="assistant-reply">{reply}</div>}<div className="ask-box"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Ask about this well…"/><button onClick={()=>ask()}><Send size={15}/></button></div></article>
  <article className="panel audit-panel"><Title icon={<ClipboardCheck/>} title="Decision trace" detail="Latest simulated actions"/><div className="audit-list">{actions.length?actions.map((a,i)=><div key={`${a.timestamp}-${i}`}><i className="audit-dot"/><section><b>{a.event.replaceAll('_',' ')}</b><p>{a.detail}</p></section><time>{new Date(a.timestamp*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div>):<p className="empty">No actions recorded yet.</p>}</div></article></section></section></main>;
}
function Metric({label,value,icon}){return <div className="metric"><i>{icon}</i><div><small>{label}</small><strong>{value}</strong></div></div>}; function Point({label,value}){return <div><small>{label}</small><b>{value}</b></div>}; function Item({label,value,sub}){return <div className="data-item"><small>{label}</small><strong>{value}</strong>{sub&&<span>{sub}</span>}</div>}; function Title({icon,title,detail}){return <div className="panel-title"><i>{icon}</i><div><h2>{title}</h2><p>{detail}</p></div></div>}; function Range({label,value,unit,min,max,step=1,disabled,onChange}){return <div className="range-field"><label>{label}<b>{n(value,step<1?1:0)} {unit}</b></label><input type="range" min={min} max={max} step={step} value={value} disabled={disabled} onChange={e=>onChange(Number(e.target.value))}/><span>{min}<i/>{max} {unit}</span></div>}; function EconomicInput({label,value,step,onChange}){return <label className="number-input"><span>{label}</span><div><i>$</i><input type="number" value={value} step={step} onChange={e=>onChange(Number(e.target.value))}/></div></label>};
